global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Etmen_Domain.Entities;
global using Etmen_Domain.Enums;
global using Etmen_DAL.Repositories.Interfaces;
global using Etmen_BLL.DTOs;
global using Etmen_BLL.Repositories.IServices;
global using Etmen_BLL.DTOs.Alert;
global using Etmen_BLL.DTOs.Doctor;
global using Etmen_BLL.DTOs.Emergency;
global using Etmen_BLL.DTOs.Family;
global using Etmen_BLL.DTOs.Lab;
global using Etmen_BLL.DTOs.Medical;
global using Etmen_BLL.DTOs.Nearby;
global using Etmen_BLL.DTOs.Notification;
global using Etmen_BLL.DTOs.Patient;
global using Etmen_BLL.DTOs.Risk;
global using Etmen_BLL.Helpers;
global using Mapster;
global using System.Text.Json;
global using MedicalRecordCreateDto = Etmen_BLL.DTOs.Medical.MedicalRecordCreateDto;
global using PatientAlertDto = Etmen_BLL.DTOs.Alert.PatientAlertDto;
global using Etmen_BLL.DTOs.Admin;
global using Etmen_BLL.DTOs.Auth;
global using Etmen_BLL.DTOs.Chat;
global using Etmen_BLL.DTOs.Crisis;

global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using System.Net;
global using System.Net.Mail;

global using Etmen_BLL.DTOs.HospitalStaff;
global using Microsoft.AspNetCore.Identity;
