using Etmen_BLL.DTOs.Emergency;

namespace Etmen_PL.Models.ViewModels.Hospital
{
    public class HospitalQueueViewModel
    {
        public int? ProviderId { get; set; }
        public string? ProviderName { get; set; }
        public string? ProviderAddress { get; set; }
        public string? AdminUserId { get; set; }
        public decimal? ProviderLatitude { get; set; }
        public decimal? ProviderLongitude { get; set; }
        public int PendingCount { get; set; }
        public int AcceptedCount { get; set; }
        public int EscalatedCount { get; set; }
        public int? AvailableBeds { get; set; }
        public List<HospitalQueueItemViewModel> Items { get; set; } = new();
    }

    public class HospitalQueueItemViewModel
    {
        public int RequestId { get; set; }
        public int PatientProfileId { get; set; }
        public string PatientName { get; set; } = string.Empty;
        public string? PatientPhone { get; set; }
        public string EmergencyType { get; set; } = string.Empty;
        public string Status { get; set; } = string.Empty;
        public DateTime RequestedAt { get; set; }
        public int WaitingMinutes { get; set; }
        public bool IsAutoGenerated { get; set; }
        public int PriorityScore { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public string? ReferringDoctorName { get; set; }
        public string? Notes { get; set; }
    }
}
