

namespace Etmen_DAL.Configurations
{
    public class EmergencyRequestConfig : IEntityTypeConfiguration<EmergencyRequest>
    {
        public void Configure(EntityTypeBuilder<EmergencyRequest> builder)
        {
            builder.HasKey(x => x.Id);

            builder.Property(x => x.PatientProfileId)
                .IsRequired();

            builder.HasOne(x => x.PatientProfile)
                .WithMany(p => p.EmergencyRequests)
                .HasForeignKey(x => x.PatientProfileId)
                .OnDelete(DeleteBehavior.Restrict); 

            builder.HasOne(x => x.RiskAssessment)
                .WithMany()
                .HasForeignKey(x => x.RiskAssessmentId)
                .OnDelete(DeleteBehavior.SetNull);

            builder.HasOne(x => x.HealthcareProvider)
                .WithMany()
                .HasForeignKey(x => x.HealthcareProviderId)
                .OnDelete(DeleteBehavior.SetNull);

            builder.HasOne(x => x.AssignedDoctor)
                .WithMany()
                .HasForeignKey(x => x.AssignedDoctorUserId)
                .OnDelete(DeleteBehavior.SetNull);

            builder.HasOne(x => x.RespondedByUser)
                .WithMany()
                .HasForeignKey(x => x.RespondedByUserId)
                .OnDelete(DeleteBehavior.Restrict);

            builder.Property(x => x.EmergencyType)
                .HasMaxLength(500);

            builder.Property(x => x.Description)
                .HasMaxLength(1000);

            builder.Property(x => x.Latitude)
                .HasColumnType("decimal(9,6)");

            builder.Property(x => x.Longitude)
                .HasColumnType("decimal(9,6)");

            builder.Property(x => x.ResponseNotes)
                .HasMaxLength(500);

            builder.Property(x => x.IsAutoGenerated)
                .HasDefaultValue(false);

            builder.Property(x => x.PriorityScore)
                .HasDefaultValue(0);

            builder.Property(x => x.EscalationReason)
                .HasMaxLength(1000);

            builder.Property(x => x.RequestedAt)
                .IsRequired();

            builder.HasIndex(x => x.Status);
            builder.HasIndex(x => x.RequestedAt);
            builder.HasIndex(x => x.PriorityScore);
            builder.HasIndex(x => x.IsAutoGenerated);
            builder.HasIndex(x => x.RiskAssessmentId);
            builder.HasIndex(x => x.AssignedDoctorUserId);
        }
    }
}
