using Etmen_Domain.Enums;

namespace Etmen_BLL.DTOs.CriticalCare
{
    public class CriticalCareCaseDto
    {
        public int EmergencyRequestId { get; set; }
        public int? RiskAssessmentId { get; set; }
        public int PatientProfileId { get; set; }
        public string PatientName { get; set; } = string.Empty;
        public string? PatientPhone { get; set; }
        public decimal RiskScore { get; set; }
        public RiskLevel RiskLevel { get; set; }
        public string? Symptoms { get; set; }
        public EmergencyRequestStatus EmergencyStatus { get; set; }
        public int PriorityScore { get; set; }
        public bool IsAutoGenerated { get; set; }
        public DateTime RequestedAt { get; set; }
        public DateTime? AcceptedAt { get; set; }
        public DateTime? CompletedAt { get; set; }
        public string? AssignedProviderName { get; set; }
        public bool DoctorsNotified { get; set; }
        public DateTime? DoctorsNotifiedAt { get; set; }
        public bool HasDoctorConversation { get; set; }
        public DateTime? LastDoctorMessageAt { get; set; }
        public bool EmergencyResponded => AcceptedAt.HasValue || EmergencyStatus is EmergencyRequestStatus.Accepted or EmergencyRequestStatus.Completed;
    }
}
