using Etmen_Domain.Enums;

namespace Etmen_BLL.DTOs.HospitalStaff
{
    public class HospitalStaffQueueDto
    {
        public int? ProviderId { get; set; }
        public string? ProviderName { get; set; }
        public int PendingCount { get; set; }
        public int AcceptedCount { get; set; }
        public int EscalatedCount { get; set; }
        public int? AvailableBeds { get; set; }
        public DateTime GeneratedAt { get; set; }
        public List<HospitalStaffQueueItemDto> Items { get; set; } = new();
    }

    public class HospitalStaffQueueItemDto
    {
        public int RequestId { get; set; }
        public int PatientProfileId { get; set; }
        public string PatientName { get; set; } = string.Empty;
        public string? PatientPhone { get; set; }
        public string EmergencyType { get; set; } = string.Empty;
        public EmergencyRequestStatus Status { get; set; }
        public DateTime RequestedAt { get; set; }
        public int WaitingMinutes { get; set; }
        public bool IsAutoGenerated { get; set; }
        public int PriorityScore { get; set; }
        public string? EscalationReason { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public int? AssignedProviderId { get; set; }
        public string? AssignedProviderName { get; set; }
    }
}
