using Etmen_BLL.DTOs.CriticalCare;
using Etmen_BLL.DTOs.Risk;
using Etmen_BLL.Helpers;
using Etmen_BLL.Repositories.IServices;
using Etmen_DAL.Repositories.Interfaces;
using Etmen_Domain.Entities;
using Etmen_Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace Etmen_BLL.Repositories.Services
{
    public sealed class CriticalCareEscalationService : ICriticalCareEscalationService
    {
        private static readonly EmergencyRequestStatus[] ActiveEmergencyStatuses =
        [
            EmergencyRequestStatus.Pending,
            EmergencyRequestStatus.Accepted,
            EmergencyRequestStatus.Escalated
        ];

        private readonly IUnitOfWork _uow;

        public CriticalCareEscalationService(IUnitOfWork uow)
        {
            _uow = uow;
        }

        public async Task<ServiceResult<CriticalCareEscalationDto>> EscalateIfNeededAsync(
            PatientProfile patient,
            RiskAssessment riskAssessment,
            RiskInputDto input)
        {
            if (patient is null)
                return ServiceResult<CriticalCareEscalationDto>.Failure("Patient profile is required.");
            if (riskAssessment is null)
                return ServiceResult<CriticalCareEscalationDto>.Failure("Risk assessment is required.");

            if (!ShouldEscalate(riskAssessment))
            {
                return ServiceResult<CriticalCareEscalationDto>.Success(new CriticalCareEscalationDto
                {
                    WasEscalated = false,
                    Message = "Risk level does not require automatic critical-care escalation."
                });
            }

            var existing = await _uow.EmergencyRequests.Table
                .Where(e =>
                    e.PatientProfileId == patient.Id &&
                    e.IsAutoGenerated &&
                    ActiveEmergencyStatuses.Contains(e.Status))
                .OrderByDescending(e => e.PriorityScore)
                .ThenByDescending(e => e.RequestedAt)
                .FirstOrDefaultAsync();

            if (existing is not null)
            {
                await EnsureCareTeamNotificationsAsync(patient, riskAssessment, existing);
                await _uow.CompleteAsync();

                return ServiceResult<CriticalCareEscalationDto>.Success(new CriticalCareEscalationDto
                {
                    WasEscalated = true,
                    WasAlreadyEscalated = true,
                    EmergencyRequestId = existing.Id,
                    PriorityScore = existing.PriorityScore,
                    EmergencyStatus = existing.Status,
                    Message = "Patient already has an active automatic critical emergency request."
                });
            }

            var priorityScore = CalculatePriorityScore(riskAssessment);
            var request = new EmergencyRequest
            {
                PatientProfileId = patient.Id,
                RiskAssessmentId = riskAssessment.Id == 0 ? null : riskAssessment.Id,
                EmergencyType = "AutoCriticalRisk",
                Description = BuildEmergencyDescription(patient, riskAssessment, input),
                Latitude = input.Latitude,
                Longitude = input.Longitude,
                Status = EmergencyRequestStatus.Escalated,
                RequestedAt = DateTime.UtcNow,
                IsAutoGenerated = true,
                PriorityScore = priorityScore,
                AutoEscalatedAt = DateTime.UtcNow,
                EscalationReason = BuildEscalationReason(riskAssessment)
            };

            await _uow.EmergencyRequests.AddAsync(request);
            await EnsureCareTeamNotificationsAsync(patient, riskAssessment, request);
            await _uow.CompleteAsync();

            return ServiceResult<CriticalCareEscalationDto>.Created(new CriticalCareEscalationDto
            {
                WasEscalated = true,
                EmergencyRequestId = request.Id,
                PriorityScore = request.PriorityScore,
                EmergencyStatus = request.Status,
                Message = "Automatic critical-care escalation was created."
            });
        }

        public async Task<ServiceResult<List<CriticalCareCaseDto>>> GetCriticalCasesAsync(
            bool includeResolved = false,
            int take = 100)
        {
            take = Math.Clamp(take, 1, 500);

            var query = _uow.EmergencyRequests.Table
                .Include(e => e.PatientProfile)
                    .ThenInclude(p => p.ApplicationUser)
                .Include(e => e.HealthcareProvider)
                .Include(e => e.RiskAssessment)
                .Where(e => e.IsAutoGenerated);

            if (!includeResolved)
            {
                query = query.Where(e =>
                    e.Status != EmergencyRequestStatus.Completed &&
                    e.Status != EmergencyRequestStatus.Cancelled);
            }

            var cases = await query
                .OrderByDescending(e => e.PriorityScore)
                .ThenBy(e => e.RequestedAt)
                .Take(take)
                .ToListAsync();

            var doctorUserIds = await _uow.DoctorProfiles.Table
                .Where(d => d.ApplicationUserId != string.Empty)
                .Select(d => d.ApplicationUserId)
                .ToListAsync();

            var result = new List<CriticalCareCaseDto>();
            foreach (var emergency in cases)
            {
                var patientUserId = emergency.PatientProfile.ApplicationUserId;
                var doctorMessages = await _uow.ChatMessages.Table
                    .Where(m =>
                        doctorUserIds.Contains(m.SenderId) && m.ReceiverId == patientUserId ||
                        doctorUserIds.Contains(m.ReceiverId) && m.SenderId == patientUserId)
                    .OrderByDescending(m => m.SentAt)
                    .ToListAsync();

                result.Add(new CriticalCareCaseDto
                {
                    EmergencyRequestId = emergency.Id,
                    RiskAssessmentId = emergency.RiskAssessmentId,
                    PatientProfileId = emergency.PatientProfileId,
                    PatientName = emergency.PatientProfile.FullName ?? "Unknown patient",
                    PatientPhone = emergency.PatientProfile.ApplicationUser?.PhoneNumber,
                    RiskScore = emergency.RiskAssessment?.RiskScore ?? 0,
                    RiskLevel = emergency.RiskAssessment?.RiskLevel ?? RiskLevel.Emergency,
                    Symptoms = emergency.RiskAssessment?.Symptoms,
                    EmergencyStatus = emergency.Status,
                    PriorityScore = emergency.PriorityScore,
                    IsAutoGenerated = emergency.IsAutoGenerated,
                    RequestedAt = emergency.RequestedAt,
                    AcceptedAt = emergency.AcceptedAt,
                    CompletedAt = emergency.CompletedAt,
                    AssignedProviderName = emergency.HealthcareProvider?.Name,
                    DoctorsNotified = emergency.DoctorsNotified,
                    DoctorsNotifiedAt = emergency.DoctorsNotifiedAt,
                    HasDoctorConversation = doctorMessages.Count > 0,
                    LastDoctorMessageAt = doctorMessages.FirstOrDefault()?.SentAt
                });
            }

            return ServiceResult<List<CriticalCareCaseDto>>.Success(result);
        }

        private async Task EnsureCareTeamNotificationsAsync(
            PatientProfile patient,
            RiskAssessment riskAssessment,
            EmergencyRequest emergencyRequest)
        {
            if (!emergencyRequest.DoctorsNotified)
            {
                var doctors = await _uow.DoctorProfiles.Table
                    .Include(d => d.ApplicationUser)
                    .Where(d => d.IsAvailable && d.ApplicationUserId != string.Empty)
                    .ToListAsync();

                foreach (var doctor in doctors)
                {
                    await AddAlertAsync(
                        doctor.ApplicationUserId,
                        "Critical patient requires immediate review",
                        BuildDoctorMessage(patient, riskAssessment),
                        "CriticalCare");

                    await AddNotificationAsync(
                        doctor.ApplicationUserId,
                        "Critical patient alert",
                        BuildDoctorMessage(patient, riskAssessment),
                        $"/Doctor/Patients/Detail/{patient.Id}");
                }

                emergencyRequest.DoctorsNotified = true;
                emergencyRequest.DoctorsNotifiedAt = DateTime.UtcNow;
            }

            emergencyRequest.AdminNotified = true;
            emergencyRequest.AdminNotifiedAt ??= DateTime.UtcNow;

            await AddAlertAsync(
                patient.ApplicationUserId,
                "Emergency escalation started",
                "Your latest risk assessment was critical. The care team and emergency queue have been notified automatically.",
                "AutoEmergency");

            _uow.EmergencyRequests.Update(emergencyRequest);
        }

        private async Task AddAlertAsync(string userId, string title, string message, string type)
        {
            await _uow.Alerts.AddAsync(new Alert
            {
                UserId = userId,
                Title = title,
                Message = message,
                AlertType = type,
                Status = AlertStatus.Unread,
                CreatedAt = DateTime.UtcNow
            });
        }

        private async Task AddNotificationAsync(string userId, string title, string message, string link)
        {
            await _uow.Notifications.AddAsync(new Notification
            {
                UserId = userId,
                Title = title,
                Message = message,
                Link = link,
                CreatedAt = DateTime.UtcNow
            });
        }

        private static bool ShouldEscalate(RiskAssessment riskAssessment)
            => riskAssessment.IsEmergency ||
               riskAssessment.RiskLevel is RiskLevel.High or RiskLevel.Critical or RiskLevel.Emergency ||
               riskAssessment.RiskScore >= 0.70m;

        private static int CalculatePriorityScore(RiskAssessment riskAssessment)
        {
            var baseScore = riskAssessment.RiskLevel switch
            {
                RiskLevel.Emergency => 1000,
                RiskLevel.Critical => 900,
                RiskLevel.High => 800,
                _ => 700
            };

            return baseScore + (int)Math.Round(riskAssessment.RiskScore * 100);
        }

        private static string BuildEmergencyDescription(
            PatientProfile patient,
            RiskAssessment riskAssessment,
            RiskInputDto input)
            => $"Automatic escalation for {patient.FullName ?? "patient"} after high risk score. " +
               $"RiskScore={riskAssessment.RiskScore:P0}, Level={riskAssessment.RiskLevel}, Symptoms={riskAssessment.Symptoms ?? "N/A"}, " +
               $"Vitals: BP={input.SystolicBP}/{input.DiastolicBP}, HR={input.HeartRate}, Temp={input.Temperature}, O2={input.OxygenSaturation}, Sugar={input.BloodSugar}.";

        private static string BuildEscalationReason(RiskAssessment riskAssessment)
            => $"Risk assessment reached {riskAssessment.RiskLevel} with score {riskAssessment.RiskScore:P0}.";

        private static string BuildDoctorMessage(PatientProfile patient, RiskAssessment riskAssessment)
            => $"{patient.FullName ?? "A patient"} has a critical risk assessment. " +
               $"Score: {riskAssessment.RiskScore:P0}. Level: {riskAssessment.RiskLevel}. Symptoms: {riskAssessment.Symptoms ?? "N/A"}. " +
               "Please review the profile and start patient contact if clinically appropriate.";
    }
}
