using Etmen_BLL.DTOs.HospitalStaff;
using Etmen_BLL.Helpers;
using Etmen_BLL.Repositories.IServices;
using Etmen_DAL.Repositories.Interfaces;
using Etmen_Domain.Entities;
using Etmen_Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace Etmen_BLL.Repositories.Services
{
    public sealed class HospitalStaffService : IHospitalStaffService
    {
        private static readonly EmergencyRequestStatus[] QueueStatuses =
        [
            EmergencyRequestStatus.Pending,
            EmergencyRequestStatus.Accepted,
            EmergencyRequestStatus.Escalated
        ];

        private readonly IUnitOfWork _uow;

        public HospitalStaffService(IUnitOfWork uow)
        {
            _uow = uow;
        }

        public async Task<ServiceResult<HospitalStaffQueueDto>> GetQueueAsync(int? providerId = null)
        {
            HealthcareProvider? provider = null;
            if (providerId.HasValue)
            {
                provider = await _uow.HealthcareProviders.GetByIdAsync(providerId.Value);
                if (provider is null)
                    return ServiceResult<HospitalStaffQueueDto>.NotFound("Healthcare provider was not found.");
                if (!provider.IsEmergencyCenter)
                    return ServiceResult<HospitalStaffQueueDto>.Failure("Provider is not configured as an emergency center.");
            }

            var query = _uow.EmergencyRequests.Table
                .Include(e => e.PatientProfile)
                    .ThenInclude(p => p.ApplicationUser)
                .Include(e => e.HealthcareProvider)
                .Where(e => QueueStatuses.Contains(e.Status));

            if (providerId.HasValue)
            {
                query = query.Where(e =>
                    e.HealthcareProviderId == providerId.Value ||
                    e.HealthcareProviderId == null && e.Status != EmergencyRequestStatus.Accepted);
            }

            var requests = await query
                .OrderByDescending(e => e.IsAutoGenerated)
                .ThenByDescending(e => e.PriorityScore)
                .ThenByDescending(e => e.Status == EmergencyRequestStatus.Escalated)
                .ThenBy(e => e.RequestedAt)
                .ToListAsync();

            var dto = new HospitalStaffQueueDto
            {
                ProviderId = provider?.Id,
                ProviderName = provider?.Name,
                AvailableBeds = provider?.AvailableBeds,
                PendingCount = requests.Count(e => e.Status == EmergencyRequestStatus.Pending),
                AcceptedCount = requests.Count(e => e.Status == EmergencyRequestStatus.Accepted),
                EscalatedCount = requests.Count(e => e.Status == EmergencyRequestStatus.Escalated),
                GeneratedAt = DateTime.UtcNow,
                Items = requests.Select(MapQueueItem).ToList()
            };

            return ServiceResult<HospitalStaffQueueDto>.Success(dto);
        }

        public async Task<ServiceResult<HospitalStaffEmergencyDetailDto>> GetRequestDetailAsync(int requestId, int? providerId = null)
        {
            if (requestId <= 0)
                return ServiceResult<HospitalStaffEmergencyDetailDto>.Failure("Request id is required.");

            var request = await _uow.EmergencyRequests.Table
                .Include(e => e.PatientProfile)
                    .ThenInclude(p => p.ApplicationUser)
                .Include(e => e.HealthcareProvider)
                .FirstOrDefaultAsync(e => e.Id == requestId);

            if (request is null)
                return ServiceResult<HospitalStaffEmergencyDetailDto>.NotFound("Emergency request was not found.");

            if (providerId.HasValue && request.HealthcareProviderId.HasValue && request.HealthcareProviderId != providerId.Value)
                return ServiceResult<HospitalStaffEmergencyDetailDto>.Forbidden("This emergency request is assigned to another provider.");

            return ServiceResult<HospitalStaffEmergencyDetailDto>.Success(MapDetail(request));
        }

        public async Task<ServiceResult> RespondToRequestAsync(HospitalStaffEmergencyRespondDto dto)
        {
            var errors = ValidateResponse(dto).ToList();
            if (errors.Count > 0)
                return ServiceResult.Failure(errors);

            if (!Enum.TryParse<EmergencyRequestStatus>(dto.Status, true, out var requestedStatus))
                return ServiceResult.Failure("Emergency request status is invalid.");

            if (!IsStaffActionStatus(requestedStatus))
                return ServiceResult.Failure("Hospital staff can only accept, reject, escalate, complete, or cancel emergency requests.");

            var provider = await _uow.HealthcareProviders.GetByIdAsync(dto.ProviderId);
            if (provider is null)
                return ServiceResult.NotFound("Healthcare provider was not found.");
            if (!provider.IsEmergencyCenter || !provider.IsActive)
                return ServiceResult.Failure("Provider must be an active emergency center.");

            var request = await _uow.EmergencyRequests.GetByIdAsync(dto.RequestId);
            if (request is null)
                return ServiceResult.NotFound("Emergency request was not found.");

            if (request.HealthcareProviderId.HasValue && request.HealthcareProviderId != dto.ProviderId)
                return ServiceResult.Forbidden("This emergency request is assigned to another provider.");

            var transitionError = ValidateTransition(request.Status, requestedStatus, dto.ResponseNotes);
            if (transitionError is not null)
                return ServiceResult.Failure(transitionError);

            if (requestedStatus == EmergencyRequestStatus.Accepted && (provider.AvailableBeds ?? 0) <= 0)
                return ServiceResult.Conflict("No available emergency beds for this provider.");

            ApplyResponse(request, provider, requestedStatus, dto.ResponseNotes);

            _uow.EmergencyRequests.Update(request);
            _uow.HealthcareProviders.Update(provider);
            await _uow.CompleteAsync();

            return ServiceResult.Success();
        }

        public async Task<ServiceResult> UpdateBedsAsync(HospitalStaffBedsUpdateDto dto)
        {
            if (dto is null)
                return ServiceResult.Failure("Beds update payload is required.");
            if (dto.ProviderId <= 0)
                return ServiceResult.Failure("Provider id is required.");
            if (dto.AvailableBeds < 0)
                return ServiceResult.Failure("Available beds cannot be negative.");
            if (dto.AvailableBeds > 10000)
                return ServiceResult.Failure("Available beds value is outside the accepted range.");

            var provider = await _uow.HealthcareProviders.GetByIdAsync(dto.ProviderId);
            if (provider is null)
                return ServiceResult.NotFound("Healthcare provider was not found.");
            if (!provider.IsEmergencyCenter)
                return ServiceResult.Failure("Provider is not configured as an emergency center.");

            provider.AvailableBeds = dto.AvailableBeds;
            _uow.HealthcareProviders.Update(provider);
            await _uow.CompleteAsync();

            return ServiceResult.Success();
        }

        private static HospitalStaffQueueItemDto MapQueueItem(EmergencyRequest request)
        {
            var waitingMinutes = (int)Math.Max(0, (DateTime.UtcNow - request.RequestedAt).TotalMinutes);

            return new HospitalStaffQueueItemDto
            {
                RequestId = request.Id,
                PatientProfileId = request.PatientProfileId,
                PatientName = request.PatientProfile?.FullName ?? "Unknown patient",
                PatientPhone = request.PatientProfile?.ApplicationUser?.PhoneNumber,
                EmergencyType = request.EmergencyType ?? "Unspecified",
                Status = request.Status,
                RequestedAt = request.RequestedAt,
                WaitingMinutes = waitingMinutes,
                IsAutoGenerated = request.IsAutoGenerated,
                PriorityScore = request.PriorityScore,
                EscalationReason = request.EscalationReason,
                Latitude = request.Latitude,
                Longitude = request.Longitude,
                AssignedProviderId = request.HealthcareProviderId,
                AssignedProviderName = request.HealthcareProvider?.Name
            };
        }

        private static HospitalStaffEmergencyDetailDto MapDetail(EmergencyRequest request) => new()
        {
            RequestId = request.Id,
            Status = request.Status,
            EmergencyType = request.EmergencyType ?? "Unspecified",
            Description = request.Description,
            RequestedAt = request.RequestedAt,
            AcceptedAt = request.AcceptedAt,
            CompletedAt = request.CompletedAt,
            ResponseNotes = request.ResponseNotes,
            PatientProfileId = request.PatientProfileId,
            PatientName = request.PatientProfile?.FullName ?? "Unknown patient",
            PatientPhone = request.PatientProfile?.ApplicationUser?.PhoneNumber,
            PatientEmail = request.PatientProfile?.ApplicationUser?.Email,
            BloodType = request.PatientProfile?.BloodType,
            HasChronicDiseases = request.PatientProfile?.HasChronicDiseases ?? false,
            ChronicDiseasesNotes = request.PatientProfile?.ChronicDiseasesNotes,
            Allergies = request.PatientProfile?.Allergies,
            CurrentMedications = request.PatientProfile?.CurrentMedications,
            Latitude = request.Latitude,
            Longitude = request.Longitude,
            AssignedProviderId = request.HealthcareProviderId,
            AssignedProviderName = request.HealthcareProvider?.Name,
            AssignedProviderPhone = request.HealthcareProvider?.Phone,
            AssignedProviderAvailableBeds = request.HealthcareProvider?.AvailableBeds
        };

        private static IEnumerable<string> ValidateResponse(HospitalStaffEmergencyRespondDto dto)
        {
            if (dto is null)
            {
                yield return "Emergency response payload is required.";
                yield break;
            }

            if (dto.RequestId <= 0)
                yield return "Request id is required.";
            if (dto.ProviderId <= 0)
                yield return "Provider id is required.";
            if (string.IsNullOrWhiteSpace(dto.Status))
                yield return "Response status is required.";
        }

        private static bool IsStaffActionStatus(EmergencyRequestStatus status)
            => status is EmergencyRequestStatus.Accepted
                or EmergencyRequestStatus.Rejected
                or EmergencyRequestStatus.Escalated
                or EmergencyRequestStatus.Completed
                or EmergencyRequestStatus.Cancelled;

        private static string? ValidateTransition(EmergencyRequestStatus current, EmergencyRequestStatus next, string? notes)
        {
            if (current is EmergencyRequestStatus.Completed or EmergencyRequestStatus.Cancelled)
                return "Completed or cancelled requests cannot be changed.";

            if (current == EmergencyRequestStatus.Rejected && next != EmergencyRequestStatus.Escalated)
                return "Rejected requests can only be escalated.";

            if (next is EmergencyRequestStatus.Rejected or EmergencyRequestStatus.Cancelled or EmergencyRequestStatus.Escalated &&
                string.IsNullOrWhiteSpace(notes))
                return "Response notes are required for rejection, cancellation, or escalation.";

            if (next == EmergencyRequestStatus.Completed && current != EmergencyRequestStatus.Accepted)
                return "Only accepted emergency requests can be completed.";

            return null;
        }

        private static void ApplyResponse(
            EmergencyRequest request,
            HealthcareProvider provider,
            EmergencyRequestStatus status,
            string? notes)
        {
            request.Status = status;
            request.ResponseNotes = string.IsNullOrWhiteSpace(notes) ? request.ResponseNotes : notes.Trim();

            switch (status)
            {
                case EmergencyRequestStatus.Accepted:
                    request.HealthcareProviderId = provider.Id;
                    request.AcceptedAt ??= DateTime.UtcNow;
                    provider.AvailableBeds = Math.Max(0, (provider.AvailableBeds ?? 0) - 1);
                    break;
                case EmergencyRequestStatus.Completed:
                    request.CompletedAt ??= DateTime.UtcNow;
                    break;
                case EmergencyRequestStatus.Rejected:
                case EmergencyRequestStatus.Escalated:
                case EmergencyRequestStatus.Cancelled:
                    request.HealthcareProviderId ??= provider.Id;
                    break;
            }
        }
    }
}
